pipeline {
    agent any

    tools {
        nodejs "NodeJS_18"
    }

    environment {

        AWS_REGION = "ap-south-1"
        S3_BUCKET  = "seatifyai.com"
        CLOUDFRONT_DISTRIBUTION_ID = "E1PUT3P1605C1O"
    }

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main',
                url: 'https://github.com/Shanmu-iHub/New-Seatifyai.git'
            }
        }

        stage('Check Node & npm') {
            steps {
                sh 'node -v'
                sh 'npm -v'
            }
        }

        stage('Install Frontend Dependencies') {
            steps {

                dir('frontend') {

                    sh '''
                    npm install
                    '''
                }
            }
        }

        stage('Build Frontend') {
            steps {

                dir('frontend') {

                    sh '''
                    CI=false npm run build
                    '''
                }
            }
        }

        stage('Upload to S3') {
            steps {

                dir('frontend') {

                    sh '''
                    aws s3 sync build s3://$S3_BUCKET/ \
                    --region $AWS_REGION \
                    --delete
                    '''
                }
            }
        }

        stage('Invalidate CloudFront') {
            steps {

                sh '''
                aws cloudfront create-invalidation \
                --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
                --paths "/*"
                '''
            }
        }
    }

    post {

        success {
            echo ':white_check_mark: Frontend Deployment Successful!'
        }

        failure {
            echo ':x: Frontend Deployment Failed!'
        }
    }
}